### ISSUE TITLE
Elements in Stage 2 are shown in the tree

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#114]
I created a location profile and stated that my StageNumber is eq 1. When I view the tree, I am able to see elements from Stage 2. That is not good. I do not  want to see elements from stage 2

**Comment by nickImbirev** [comment]
The root of the issue is E4E searching process. When we are searching for elements - we are doing it **up to the Endevor map**, which means that we will try to find any available element not only in current location, but in the following stages as well.

I can suggest to implement a new VSCode setting in E4E to have an ability to configure the search process. If the setting will be activated - we will search elements as we are doing it today, if not - we will search elements only in specified location.

@RedGoldPhoenix what do you think about it?

**Comment by nickImbirev** [comment]
This issue is related to #113

**Comment by RedGoldPhoenix** [comment]
@nickImbirev 

Hello Nikolai sorry for the delay in my answer.

That's interesting ;)
My goal is really to check only on the stage and not to have the element upper.
If you can implement that could be great ;)

Best Regards

**Comment by jellypuno** [comment]
Possibly Handled in Sync Research

**Comment by VitGottwald** [comment]
Currently all elements from the specified location and _up_ are displayed together and we have heard from many users that it is confusing. 

We are going list only the elements from the specified location directly under the _type_ folder. The rest of the elements will move into a new _folder_ called *map*. Unless the user expands the *map* folder they will only see elements from the location they specified in the location profile as asked for by @RedGoldPhoenix .

In addition to that when the user chooses to expand the *map* folder to see the elements from _up the map_ these elements will contain a "tag" showing where exactly they came from.

**Comment by VitGottwald** [comment]
For example lets assume we have 2 Cobol programs PROG0001 and PROG0002 in system `Finance`, subsystem `Acctrec`, environment `SMPLTEST`, stage 1. The next system up the map is `Finance/Acctrec/SMPLPROD/2` and it contains programs PROG0003 and PROG0004.

This is what the user will see after expanding the Cobol (type) folder:

```
⌄ Finance
  ⌄ Acctrec
    ⌄ Cobol
        > map
        PROG0001
        PROG0001
```

After expanding the *map* folder, it would look like this:

```
⌄ Finance
  ⌄ Acctrec
    ⌄ Cobol
        ⌄ map
          PROG0003 [SMPLPROD/2]
          PROG0004 [SMPLPROD/2]
        PROG0001
        PROG0001
```
