### ISSUE TITLE
Enhancement request - Click the element to browse it by default

### ISSUE THREAD

**Issue by radecek9787** [eclipse/che-che4z-explorer-for-endevor#13]
When I use VS Code explorer or Zowe plugin under VS Code to display MVS datasets and members, I just click the desired member or file and it is opened on the right panel so I can browse it immediately. 

Using Explorer for Endevor, I need to first right-click the element and then select Browse Element. This is not so intuitive for me. I would expect the element to be opened in browse mode by default when I click it like the other explorers in VS Code work.

**Comment by FALLAI-Denis** [comment]
"BROWSE" (that is a "PRINT") or "RETRIEVE" ?

**Comment by zdmullen** [comment]
Hey @radecek9787 and @FALLAI-Denis, we will actually be updating this behavior soon. The feedback we've received from several folks is that a Browse as in Print (as Denis noted) is most desirable. 

We're planning to do this also because we will soon work on implementing a Quick Edit feature in Explorer for Endevor, meaning that you will be able to retrieve an element to your workspace (as a kind of virtual document, similar to the behavior in Zowe Explorer, if you are familiar), make edits, and save it to a specified location (either connected to your endevor-location profile, or based on what you enter in the prompts). 

So in the not too distant future, a normal click on an element will give you the Print view. On right + click, you will have the options:

"Quick Edit"
"Retrieve"
"Retrieve with dependencies"

The last two will have the same behavior as they do today. What do you think?

**Comment by jellypuno** [comment]
@radecek9787 We have implemented this in v0.12.1. Can we close this issue?

**Comment by radecek9787** [comment]
Hi @jellypuno, that is great, thank you! Yes, you can close the issue.
