### ISSUE TITLE
Add .prnt suffix for endevor print output

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-explorer-for-endevor#145]

**Comment by nickImbirev** [comment]
can be part of #127

**Comment by nickImbirev** [comment]
Hey @VitGottwald ! Thank you for submitting it!

What is the benefit of showing `.prnt` extension in the print output? 

As far as I understood, we try to use `fileExtension` from Endevor here to provide at least basic syntax highlighting. Do you think we don't need it? It will be better to have a plain text? 

Can we consider `.txt` as an alternative?

**Comment by FALLAI-Denis** [comment]
Currently, the resulting files are suffixed with the Type Endevor, which causes the VS Code editor to try to interpret the listing of a "print" of a COBOL Element as being a COBOL source.

I think a .txt suffix is much more suitable.

However, since several Element Endevors of different types can have the same name, the suffix would have to be the concatenation of the Type and ".txt".
For example: PROGRAM.COBOL.txt

It is important that the terminal suffix is chosen so that the editor applies the correct visualization, (syntax highlighting, search for errors in the source, etc.).

**Comment by nickImbirev** [comment]
resolved within #181 PR
