### ISSUE TITLE
Question: How to configure Endevor Web Services to get Elements encoded in UTF-8 when retrieve or browse action ?

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#37]
Using the "Explorer for Endevor" extension in VSCode, we would like the information retrieved during a RETRIEVE or BROWSE to be encoded in UTF-8.

We tried to configure the Endevor Web Services (EWS) server with the options CharacterSet="UTF-8" / LFSEncoding="UTF-8", or with CharacterSet="UTF8" / LFSEncoding="UTF8", but this causes an error at EWS level during a RETRIEVE (but OK for BROWSE).

The only value that works for us is "ISO8859-1", which then causes errors on many characters and in particular French accented characters at VSCode.

```
<DataSource xmlns="http://scm.ca.com/endevor/CFG" xmlns:cfg="http://scm.ca.endevor" 
   Name="ENDEVOR" Status="Available" 
   Message="ENDEVOR Web Service" 
   Description="Endevor demo">
  <STC JobName="WSEWSSTC" 
     ProgramName="BC1PAPI0" 
     HostName="TMVS" 
     Comments="Welcome to ENDEVOR" 
     UserId="" Password="" EncryptedPassword="" 
     PoolInitSize="0" PoolIncrSize="1" PoolMaxSize="0" PoolReapTime="0" 
     UnusedTimeout="0" AgedTimeout="0" ConnectionTimeout="0" 
     ResponseTimeout="0" 
     KeepAlive="0" 
     ConnectionMaxWS="0" ConnectionMaxKBytes="0">
   <wsParameters Lang="EN" Locale="" TimeZone="GMT+0.0" 
      CharacterSet="UTF-8" CodePage="cp01147"   
      LFSEncoding="UTF-8" Encoding="cp01147"   
      ContentType="Text" 
      Trace="TestMonitorSTCPool" Traced="ALL" Version="" 
      Product=""/>
  </STC>
</DataSource>
```

Endevor for ZOWE plugin:

```
zowe endevor retrieve element COB0C7 --env ETU --sn 1 --sys SIRIS --sub S9 --typ COBOL -i ENDEVOR
[INFO] endevor action executed in location: ETU/1/SIRIS/S9 on element: COB0C7.COBOL
[INFO] Running on host: TMVS:8180 instance: ENDEVOR
Command Error:
[ERROR] return code: 0016 reason Code 0000
[ERROR] EWS1117I Request processed by SysID TMVS, STC WSEWSSTC - STC08595,!EWS1115E!
```

STC Tomcat (WSTOMSTC):
 
```
09:44:12.146 <http-nio-8180-exec-1> ERROR (c.c.e.j.EndevorSubmitCategoryL) [Internal error] STC: EWS1117I Request processed by SysID TMVS, STC WSEWSSTC - STC08595
09:44:12.146 <http-nio-8180-exec-1> ERROR (c.c.e.j.EndevorSubmitCategoryL) [Internal error] Read output file of list type : Unrecognized field "TYPE Â# ID" (class com.ca.endevor.jersey.csv2json.TypeInfo), not marked as ignorable (47 known properties: "REGR SEV", "UPDT DATE", "NEXT TYPE", "STG #", "FWD/REV CMPNT DELTA", "INCL DSN", "FWD/REV/IMG/LOG ELM DELTA", "COMPRESS BASE", "DFLT PROC GRP", "CONSOL LL", "CMPMT AUTO CONSOL LL", "DELTA DSN", "INCL DS TYPE", "UPDT USRID", "BASE DS TYPE", "FILE EXT", "CMPNT CONSOL LL", "AUTO CONSOL", "AUTO CONSOL LL", "COMPARE (T)", "DELTA DS TYPE", "STG NAME", "STG SEQ #", "SRC LNG", "CMPNT AUTO CONSOL", "DATA FORMAT", "LANG", "COMPARE (F)", "TYPE NAME", "ELEMENT RECFM", "STG ID", "BASE/IMAGE DSN", "ENV NAME", "SRC O/P DS TYPE", "PV/LB LANG", "EXPAND INCL", "DESCRIPTION", "SYS NAME", "RCD UPDT CNT", "REGR %", "SRC O/P DSN", "ELM NAME NOT ENCRYPTED", "REL ID", "SITE ID", "TYPE # ID", "UPDT TIME", "USS DELIMITER"])
 at [Source: (StringReader); line: 2, column: 32] (through reference chain: com.ca.endevor.jersey.csv2json.TypeInfo["TYPE Â# ID"])
```

**Comment by zdmullen** [comment]
Hi Denis,

Thanks for posting this issue. I will talk with some folks with the Endevor team about the configuration in web services and get back to you this week.

**Comment by dankox** [comment]
Hi Denis,
I want to ask you, did you try "ISO-8859-15" character encoding. It should cover French characters better.
With UTF-8, there might be some problems, because it covers much bigger range than is provided on mainframe.
We will look into it. But let us know if that encoding works for you better or not.

Thanks.

**Comment by FALLAI-Denis** [comment]
Thanks @dankox 

We haven't tried ISO-8859-15, but this encoding is very close to ISO-8859-1: only 8 characters apart.
ISO-8859-1 also covers the majority of French characters. ISO-8859-15 was primarily created to handle the Euro character which does not exist in ISO-8859-1.

We want to get the informations in UTF-8 because in our context all informations in VSCode, as well as all informations in GIT, are based on UTF-8.

When converting EBCDIC IBM-1147 to UTF-8, there is no problem (apart from 2 characters not displayed in VSCode, but this is a known limitation of Chromium).
In the other direction, UTF-8 to EBCDIC IBM-1147, there could be problems if some characters were not transposable in EBCDIC IBM-1147. We accept this risk.

Note that the EBCDIC IBM-1147 to ISO-8859-1 or ISO-8859-15 conversion is not perfect either, in both directions.

Note also that we have no problem when recovering sources using the ZOWE Explorer extension for VSCode, itself based on ZOWE CLI, and that with an EBCDIC IBM-1147 configuration on the mainframe, and UTF -8 for VSCode and GIT.
The sources retrieved by ZOWE Explorer are the same as those that we are trying to retrieve by Explorer for Endevor, (Endevor Elements are exported as Component in PDS "OUTPUT" s).

**Comment by dankox** [comment]
Hi Denis,
I've opened an issue for this problem in Endevor Webservice github. I think I found the root cause of this error. It is a problem in Webservice and how it deals with the data it receives from Endevor. Because of the CSV header (from Endevor API) which is passed to Webservice, it reads it incorrectly (this data are in cp037 encoding).

We need to check, if this error might appear on more places or just on the list type action (like list elements, or retrieve/add (which is using list type for type check)).

Thanks for letting us know about this problem.

**Comment by FALLAI-Denis** [comment]
Hi,

I suggest that the encoding used locally can be declared in the configuration of the @zowe/endevor-for-zowe-cli plugin, at the level of the "endevor" profile, and at the level of the commands involved in data exchanges between the plugin runtime environment and Endevor Web Services: "add", "list", "print", "queryacm", "retrieve", "view" commands.

The local encoding should also be able to be declared in the "Explorer for Endevor" extension (and passed to the @zowe/endevor-for-zowe-cli plugin command).

**Comment by dankox** [comment]
Hi Denis,
I'm sorry for late reply (kinda missed this one). So regarding the encoding, currently we have a fix ready for the original problem, so UTF-8 should be usable with different EBCDIC encoding (in some limits). 

The original error from list types, should not happened. The fix is in a testing phase and will be released after the testing is done.

As of your other suggestion, this is something which we have in backlog. I brought it up lately and create an issue for it to get it fixed. However, it needs to be fixed in Endevor Webservice first. The reason is, that currently the only way to specify encoding is thru configuration file, which is kinda cumbersome. This needs to be allowed to change thru HTTP parameters.

When it gets fixed in Webservice, it could be used in Zowe Endevor plugin and Endevor Explorer.

**Comment by jellypuno** [comment]
@FALLAI-Denis Is it okay to close this issue?

**Comment by FALLAI-Denis** [comment]
Problem still present for us...
If a fix is delivered for Endevor Web Services, do you know its reference?
Thanks.

**Comment by jellypuno** [comment]
I would suggest the [Broadcom Community page](https://community.broadcom.com/mainframesoftware/home)

@zdmullen do you have any ideas where @FALLAI-Denis can get info on fixes for the web services?

**Comment by dankox** [comment]
@FALLAI-Denis I'm sorry, I kinda missed this one.    
Here are the respective PTFs for different versions of Endevor:

SO15539 - for version 18.0
SO15234 - for version 18.1

**Comment by FALLAI-Denis** [comment]
For your information:

Our system team does'nt install SO15234... they install LU01264, arguing that LU01264 supersedes SO15234...

But problem still present:

```
zowe  endevor view element TEST1147 --typ COBOL --tf TEST1147.txt
[INFO] Running on host: TMVS:8180 instance: ENDEVOR
[INFO] VIEW executed in location: ETU/1/SIRIS/S9 on element: TEST1147.COBOL
Command Error:
[ERROR] return code: 16 reason Code: 0
[ERROR] EWS1117I Request processed by SysID TMVS, STC WSEWSSTC - STC07737
[ERROR] !EWS1115E!

On EWS server:

<DataSource xmlns="http://scm.ca.com/endevor/CFG" xmlns:cfg="http://scm.ca.endevor" Name="ENDEVOR" Status="Available" Message="ENDEVOR Web Service" Description="Endevor demo">                                                                                
  <STC JobName="WSEWSSTC" ProgramName="BC1PAPI0" HostName="TMVS" Comments="Welcome to ENDEVOR" UserId="" Password="" EncryptedPassword="" PoolInitSize="2" PoolIncrSize="1" PoolMaxSize="5" PoolReapTime="0" UnusedTimeout="0" AgedTimeout="0" ConnectionTimeout="0" ResponseTimeout="0" KeepAlive="0" ConnectionMaxWS="0" ConnectionMaxKBytes="0">                                                
    <wsParameters Lang="EN" Locale="" TimeZone="GMT+2.0" CharacterSet="UTF8" CodePage="cp01147" LFSEncoding="UTF8" Encoding="cp01147" ContentType="Text" Trace="TestMonitorSTCPool" Traced="ALL" Version="" Product=""/>                                       
  </STC>                                                                                                                   
</DataSource>     
                                                                                                         
13:54:41.305 <main> INFO  (c.c.e.e.utils.CFGChanges) Configuration ENDEVOR.cfg added.                                      
13:54:43.345 <pool-2-thread-1> INFO  (c.c.e.eapi.STCProvider) STCs initialized.                                            
08:28:06.650 <http-nio-8180-exec-8> ERROR (c.c.e.j.EndevorSubmitCategoryL) [Internal error] STC: EWS1117I Request processed by SysID TMVS, STC WSEWSSTC - STC07737                                                                                             
08:28:06.651 <http-nio-8180-exec-8> ERROR (c.c.e.j.EndevorSubmitCategoryL) [Internal error] Read output file of list type : Unrecognized field "TYPE Â# ID" (class com.ca.endevor.jersey.csv2json.TypeInfo), not marked ignorable (47 known properties: "REGR SEV", "UPDT DATE", "NEXT TYPE", "STG #", "FWD/REV CMPNT DELTA", "INCL DSN", "FWD/REV/IMG/LOG ELM DELTA", "COMPRESS BASE", "DFLT PROC GRP",  
"CONSOL LL", "CMPMT AUTO CONSOL LL", "DELTA DSN", "INCL DS TYPE", "UPDT USRID", "BASE DS TYPE", "FILE EXT", "CMPNT CONSOL LL", "AUTO CONSOL", "AUTO CONSOL LL", "COMPARE (T)", "DELTA DS TYPE", "STG NAME", "STG SEQ #", "SRC LNG", "CMPNT AUTO CONSOL", "DATA FORMAT", "LANG", "COMPARE (F)", "TYPE NAME", "ELEMENT RECFM", "STG ID", "BASE/IMAGE DSN", "ENV NAME", "SRC O/P DS TYPE", "PV/LB LANG", "EXPAND INCL", "DESCRIPTION", "SYS NAME", "RCD UPDT CNT", "REGR %", "SRC O/P DSN", "ELM NAME NOT ENCRYPTED", "REL ID", "SITE ID", "TYPE # ID", "UPDT TIME", "USS DELIMITER"])                                                                                        
 at [Source: (StringReader); line: 2, column: 32] (through reference chain: com.ca.endevor.jersey.csv2json.TypeInfo["TYPE Â# ID"])   
```

**Comment by dankox** [comment]
Hmm... that's weird. It should have it in it.
Can you please send me the first line from the STDOUT in the tomcat joblog? 
It should look similar to this:
```
11:22:38.900 <main> INFO  (c.c.e.c.SetupUtils) Endevor Webservice version: 2.3-20210317-57CB7C7
```
I want to check which exact version are you running and test against it. Thanks.

**Comment by FALLAI-Denis** [comment]
@dankox 

What I see in log:

`13:54:38.754 <main> INFO  (c.c.e.c.SetupUtils) Endevor Webservice version: 2.0-20200311-521E8A1`

**Comment by dankox** [comment]
Oh... that one is old. I mean, it's not THAT old :) but it's old... 11th of March 2020. The one you mentioned is this year fix.    
So I would guess that they might install the Endevor portion of the PTF which you were mentioning, but they did not install Endevor Webservice or update Endevor Webservice in the tomcat which you are using.

Installation of fix for Endevor Webservice in most cases has two steps, where one is running the installation thru SMP/E or MSM or CSM (or something like that), which add the new war file into some USS location (defined in the product setup).    
The second part is running the installation shell script in USS (either thru batch job, or directly on USS).

Hope this will help.

**Comment by FALLAI-Denis** [comment]
Hi,

Thank for your help.

I found ENWSUpd.sh was not run...

I have asked my system team to upgrade the version of EWS.

Inpecting new EndevorService.war (not deployed), expected version seems to be: 2.5 20210506-fce7b5b


In the meantime, I did a test from a WEB browser after finding the URL that Zowe CLI was using.

`http://host:port/EndevorService/api/v2/ENDEVOR/env/ETU/stgnum/1/sys/SIRIS/subsys/S9/type/COBOL/ele/TEST1147`

And there everything works ... I retrieve the requested element, and it is well encoded in UTF-8 ...

![image](https://user-images.githubusercontent.com/63861965/123992748-2d35fa00-d9cc-11eb-985b-f1361bff2bb1.png)

So what difference can there be between a request sent by Zowe CLI and the equivalent request sent by a WEB browser which causes one to fail and the other to succeed?

**Comment by dankox** [comment]
I'm not sure right now if we are talking about "real" retrieve or print. From the screenshot it looks like a print (not retrieve) because of the `%+102` change level prefixes.

Now, if it's really a print, then the difference is as follows.     
The real element is retrieved in UTF-8 regardless if it's print or retrieve (in case the character set in configuration is set to UTF-8). That was not a problem even before.    
However, for retrieve there is one big difference and that is that retrieve request runs `LIST TYPE` request before retrieving element (actually it nows caches that results, but nevertheless it has to list types at least once). And this is the actual request which failed in your case as the error is from LIST request not RETRIEVE request. 

The reason why it does list type is because Webservice needs to know what type of data it will get from retrieve action. It can be text or binary and this information is stored in type configuration.

Print does not do that, because print just return plain text regardless if it's binary in original or not. The content for binary might be not usable, but that's not really point of print anyway. However, retrieve needs to return exact element in a way which is usable (text or binary form).

**Comment by MichalVasak** [comment]
Hi, Vitek asked me to have a look at this issue. 

I think Danko was correct about the diagnosis, the problem in type cache was indeed fixed in September 2020, so applying maintenance to web services should help.

In the last response from the customer, they say the update script hasn't been run, so the PTF wasn't truly applied. And "in the meantime" they ask some more questions. After that, there is no more activity. 

I assume the PTF did fix the problem once it was deployed onto Tomcat, and the issue is resolved. 

Denis, can you confirm please?

Thank you,
Michal

**Comment by VitGottwald** [comment]
Thank you @MichalVasak. @FALLAI-Denis, could you, please, confirm?

**Comment by VitGottwald** [comment]
Thank you @MichalVasak! @FALLAI-Denis, could you, please, confirm the problem was fixed?

**Comment by FALLAI-Denis** [comment]
Hi,

I confirm problem has been resolved by upgrading EWS (and applying final script, not just copying new files).

Thanks.

**Comment by FALLAI-Denis** [comment]
Fixed

**Comment by VitGottwald** [comment]
Thank you for confirming @FALLAI-Denis !
