### ISSUE TITLE
Declare the Endevor instance in the endevor profile rather than in the endevor-location profile

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#44]
This issue is for the @broadcom/endevor-for-zowe-cli plugin. In the absence of a public GitHub site for this plugin, I declare it here.

It is not possible to declare an instance (--instance) by default at the endevor profile level. The instance to use can only be declared in the endevor-location profile or at the level of the zowe commands.

In general, there is only one Endevor instance declared at the Endevor Web Services server level, and this is a property of the Endevor Web Services configuration, so it would make sense that the endevor profile is the one carries this information rather than the endevor-location profile.

This may impact the operation of the Explorer for Endevor extension.

**Comment by dankox** [comment]
Hi Denis,
I am not sure if in general you have just one instance per Endevor Web Service. We actually have quite a bunch of different instances in our setup. And therefore the reason behind the location profile containing instance is, because Endevor location is bound to instance/configuration (in the end, it's the STC which contains that environment/system/subsystem).      
And because you can have more configurations in one Endevor Webservice server, it makes more sense to swap instances with location profiles when swapping actual location which I want to work with. (I hope the explanation isn't confusing)

In the end, the only draw back to have it in location profile is that you have to specify it in multiple profiles at the same time. However, that's just one more parameter to location profile. 

I don't really know the impact on Explorer for Endevor extension. I'm not quite sure what might be causing the operation problems there. Maybe it could be resolved in the extension itself by correctly using the profiles, or extracting information from them. 

If you could describe the scenario where it is impacting the operation, it might give us some hint how to approach this issue and if it should be addressed with fixing profiles or different implementation in the extension.

Thanks.

**Comment by FALLAI-Denis** [comment]
Hi,

In fact, the thought about managing the instance came to me when using commands without referring to a location, which requires re-specifying the instance each time.

Maybe it would have been necessary to manage 3 levels of profiles:
- Endevor Web Services profile : to an Endevor Web Services server (EWS)
- Instance profile : to an Endevor Instance, in a EWS, which can explicitly or implicitly  reference an EWS profile
- Location profile : to an Endevor Location, in an Instance, which can explicitly or implicitly reference an Instance profile

**Comment by dankox** [comment]
I understand what you mean.

Are you using location profiles in your cases, or you do not use them at all?
Reason behind the question is, if you are not using them, I guess the easiest solution for you would be to define one default `endevor-location` profile where you would have only `instance` property. Do not specify anything else in it and that should do the trick. 

This is how I have it setup in most cases (in the other cases, I just specify them on command line). It also helps if you are swapping `endevor` profile (the one containing host and port) to other tomcat location which has the same configuration as the previous one.

Regarding the profile split, that's definitely doable, however it would be quite a huge breaking change. I'm not sure if it would be accepted and probably should be discussed a bit more if it makes sense and what kind of benefits it would bring.

**Comment by FALLAI-Denis** [comment]
We are in the process of setting up a new Development Workshop based on VS Code and various extensions, and source management under Git / Bitbucket which will feed Endevor (only from Git / Bitbucket to Endevor, never from Endevor to Git / Bitbucket except to use Explorer for Endevor to retrieve an item that is not in Git / Bitbucket).

We haven't fully defined how to use the Endevor for Zowe CLI plugin yet. At the moment we do not use a endevor-location-profile, all information is passed on the Zowe CLI command.

**Comment by dankox** [comment]
I see. As for the current solution, the instance is in separate profile, so it means either having two profiles or having one more argument in CLI command.

There should be update coming to `zowe`, where the profiles will be fully customizable. Not sure when this should be released, but when it will be released, Endevor will adopt it and the profiles should be much better in a way, that it will really depends on user how they want them to be.     
So I'm voting for waiting for this to happen rather than trying to push breaking change to move one parameter from one profile to the other.

**Comment by FALLAI-Denis** [comment]
@dankox 

I agree.

**Comment by jellypuno** [comment]
@FALLAI-Denis Is it okay to close this issue?

**Comment by FALLAI-Denis** [comment]
Ok
