### ISSUE TITLE
Add a New Profile - prompt doesn't disappear when clicking outside the prompt area

### ISSUE THREAD

**Issue by Alex-Dumitru** [eclipse/che-che4z-explorer-for-endevor#50]
Opening the discussion to allow to cancel the action of adding a new profile in the tree by clicking outside the prompting area.

While checking the source code, I can see that the current behaviour is present on most (if not all) input boxes.

Option in case:

```
export interface InputBoxOptions {
    /**
    * Set to `true` to keep the input box open when focus moves to another part of the editor or to another window.
    */
    ignoreFocusOut?: boolean;
```

**Comment by nickImbirev** [comment]
I do not think, we need to implement this, because users can close dialogs with ESC button, but turning this flag into true, may lead to a more complicated scenarios, we cannot even think. 

For example, user will start creating a new location, then they realise, that they need to delete service, then add a new service and etc, we will not be able to guarantee that the new location profile will be created properly in this case :(

**Comment by Alexandru-Dumitru** [comment]
Hi @nickImbirev. I hope everything is well with you and the team. Since I am no longer working on this project, I do not have any strong opinion on this option. You can take ownership of this and even close it if you want to 😃. All the best!

**Comment by nickImbirev** [comment]
:)
